[tox]
envlist = py313, lint, type

[testenv]
description = run unit tests with pytest
basepython = python3.13
deps =
    pytest
    pillow
    opensimplex
commands =
    pytest tests

[testenv:lint]
description = check code style with flake8
basepython = python3.13
deps =
    flake8
commands =
    flake8 core engine layers renderer

[testenv:type]
description = run mypy type checks
basepython = python3.13
deps =
    mypy
commands =
    mypy core engine layers renderer --strict --ignore-missing-imports