SEA_LEVEL = 300.0  # meters
MAXIMUM_HEIGHT = 1500.0
LOWLANDS_PEAK = 200.0
HILLS_PEAK = 600.0

CLIMATE_BIAS = 0.2  # positive => wetter; negative => dryer
CLIMATE_SCALE = 1.2  # >1 - stronger extremes, more variery; <1 = more samey

# where the probability for deep iron deposit is highest (high hills / low mountains)
DEEP_IRON_MOST_PROBABLE_ELEVATION = 500.0
DEEP_IRON_ELEVATION_SIGMA_FALLOFF = 100.0
# No deep iron deposits below this elevation
DEEP_IRON_LOWEST_ELEVATION = 0.0
# probability for a deep vein to still randomly appear anywhere
DEEP_IRON_BASELINE_PROBABILITY = 0.01
DEEP_IRON_PEAK_PROBABILITY = 0.04
DEEP_IRON_ORE_GRADE_MEDIAN = 0.45
DEEP_IRON_ORE_GRADE_SIGMA = 0.1
DEEP_IRON_ORE_GRADE_EXTRA_RICH_PROBABILITY = 0.05
DEEP_IRON_ORE_GRADE_EXTRA_RICH_MEDIAN = 0.9
DEEP_IRON_ORE_GRADE_EXTRA_RICH_SIGMA = 0.1

# what's the probability a good source spawns a river (acts as a throttle)
RIVERS_SOURCE_RIVER_SPAWN_PROBABILITY = 0.04


SHALLOW_IRON_BASELINE_PROBABILITY = 0.02
SHALLOW_IRON_BASELINE_TONNAGE_MEAN = 40
SHALLOW_IRON_BASELINE_TONNAGE_SIGMA = 20
SHALLOW_IRON_RIVERBANK_SPAWN_PROBABILITY = 0.5
SHALLOW_IRON_RIVERBANK_TONNAGE_MEAN = 115
SHALLOW_IRON_RIVERBANK_TONNAGE_SIGMA = 40
SHALLOW_IRON_FLOODPLAIN_SPAWN_PROBABILITY = 0.3
SHALLOW_IRON_FLOODPLAIN_TONNAGE_MEAN = 150
SHALLOW_IRON_FLOODPLAIN_TONNAGE_SIGMA = 50
SHALLOW_IRON_HILL_SPAWN_PROBABILITY = 0.05
SHALLOW_IRON_HILL_TONNAGE_MEAN = 50
SHALLOW_IRON_HILL_TONNAGE_SIGMA = 20
# scaling floodplains to * river_count ** <this value>
SHALLOW_IRON_FLOODPLAIN_RIVERS_DIMINISHER = 0.8
# used to reduce by a factor the probabilities on second pass
SHALLOW_IRON_ALLUVIAL_SPREAD_DIMINISHING_FACTOR = 0.1
SHALLOW_IRON_EXTRA_RICH_PROBABILITY = 0.05
SHALLOW_IRON_EXTRA_RICH_TONNAGE_MULTIPLIER = 1.5
